// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG0M2ib9Yi5gTv45ElgLnYB2CeRdP1AtQ',
    appId: '1:583933150817:web:d765341b9d7298d85d8c20',
    messagingSenderId: '583933150817',
    projectId: 'sync-editor-87b21',
    authDomain: 'sync-editor-87b21.firebaseapp.com',
    storageBucket: 'sync-editor-87b21.firebasestorage.app',
    measurementId: 'G-9LWE93EP83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jSGSbkTkHobZCa5mWIRGPhzgPLhLp0g',
    appId: '1:583933150817:android:a3d877d911cae8315d8c20',
    messagingSenderId: '583933150817',
    projectId: 'sync-editor-87b21',
    storageBucket: 'sync-editor-87b21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmDBpYxhkfcdy1Ob4yxTevW-w648kejXs',
    appId: '1:583933150817:ios:26d591dad6b644f35d8c20',
    messagingSenderId: '583933150817',
    projectId: 'sync-editor-87b21',
    storageBucket: 'sync-editor-87b21.firebasestorage.app',
    iosBundleId: 'com.godwin.synceditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmDBpYxhkfcdy1Ob4yxTevW-w648kejXs',
    appId: '1:583933150817:ios:26d591dad6b644f35d8c20',
    messagingSenderId: '583933150817',
    projectId: 'sync-editor-87b21',
    storageBucket: 'sync-editor-87b21.firebasestorage.app',
    iosBundleId: 'com.godwin.synceditor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG0M2ib9Yi5gTv45ElgLnYB2CeRdP1AtQ',
    appId: '1:583933150817:web:c5114dd3e650a0105d8c20',
    messagingSenderId: '583933150817',
    projectId: 'sync-editor-87b21',
    authDomain: 'sync-editor-87b21.firebaseapp.com',
    storageBucket: 'sync-editor-87b21.firebasestorage.app',
    measurementId: 'G-QN1CRN39B2',
  );
}
